nodeLinker: node-modules

npmScopes:
    fortawesome:
        npmAlwaysAuth: true
        npmAuthToken: "2F406739-2B0B-4BE1-BE45-E9362FD34751"
        npmRegistryServer: "https://npm.fontawesome.com/"
